"""Shared constants for technical SEO pipeline (checklist grouping, thresholds)."""

# Maps issue type → dashboard group (Technical-SEO.txt style)
TECH_CHECKLIST_BY_TYPE: dict[str, str] = {
    "broken_internal_link": "GSC",
    "broken_internal_http_error": "GSC",
    "redirect_chain": "GSC",
    "crawl_page_non_200": "GSC",
    "robots_unreachable": "Robots",
    "robots_missing_sitemap_line": "Robots",
    "robots_sitemap_wrong_host": "Robots",
    "robots_sitemap_invalid_url": "Robots",
    "robots_sitemap_unreachable": "Robots",
    "robots_disallow_broad_querystring": "Robots",
    "robots_disallow_all": "Robots",
    "robots_wordpress_standard_blocks": "Robots",
    "sitemap_unreachable": "Sitemap",
    "sitemap_empty": "Sitemap",
    "https_not_used": "Security",
    "missing_favicon": "Onpage",
    "missing_html_lang": "International",
    "missing_title": "Onpage",
    "missing_meta_description": "Onpage",
    "missing_h1": "Onpage",
    "multiple_h1": "Onpage",
    "missing_canonical": "Onpage",
    "title_too_long": "Onpage",
    "thin_content": "Onpage",
    "images_missing_alt": "Images",
    "soft_404_heuristic": "GSC",
    "duplicate_title": "Onpage",
    "http_status_error": "Onpage",
    "pagination_missing_rel_next": "Onpage",
    "link_check_truncated": "General",
    "crawl_data_low_trust": "Crawl quality",
    "robots_noindex": "GSC",
    # Decision engine (seo_rule_engine)
    "indexability_blocked": "GSC",
    "indexability_signal_conflict": "GSC",
    "canonical_cross_host": "Onpage",
    "canonical_self_mismatch": "Onpage",
    "canonical_missing_high_value": "Onpage",
    "js_seo_risk_high": "Onpage",
    "js_seo_risk_medium": "Onpage",
    "js_shell_missing_critical": "Onpage",
    "cloaking_heuristic": "GSC",
    "robots_meta_noindex_contradiction": "GSC",
    "http_status_non_200": "GSC",
    "weak_heading_structure": "Onpage",
    "canonical_points_to_non_indexable": "GSC",
    "canonical_low_similarity_mismatch": "Onpage",
    "google_may_ignore_canonical": "GSC",
    "page_unlikely_indexed": "GSC",
    "cloaking_risk_advanced": "GSC",
}

# Tiêu đề hiển thị song ngữ (EN = ``type`` / rule_id, VI = dòng mô tả ngắn) — dashboard + /tool
CHECKLIST_TITLE_VI: dict[str, str] = {
    "broken_internal_link": "Liên kết nội bộ trả 404",
    "broken_internal_http_error": "Liên kết nội bộ lỗi HTTP (không phải 404)",
    "redirect_chain": "Chuỗi redirect dài (nhiều bước)",
    "crawl_page_non_200": "Trang crawl trả HTTP khác 200 / không có HTML",
    "robots_unreachable": "Không đọc được robots.txt",
    "robots_missing_sitemap_line": "robots.txt thiếu dòng Sitemap:",
    "robots_sitemap_wrong_host": "Sitemap trong robots sai domain",
    "robots_sitemap_invalid_url": "URL Sitemap trong robots không hợp lệ",
    "robots_sitemap_unreachable": "Sitemap khai báo nhưng không truy cập được",
    "robots_disallow_broad_querystring": "Disallow quá rộng (query string)",
    "robots_disallow_all": "Disallow toàn site (/)",
    "robots_wordpress_standard_blocks": "Chặn wp-content (WordPress — thường chuẩn)",
    "sitemap_unreachable": "Sitemap XML không đọc được",
    "sitemap_empty": "Sitemap trả 200 nhưng không có URL",
    "https_not_used": "Trang bắt đầu dùng HTTP (nên HTTPS)",
    "missing_favicon": "Thiếu favicon",
    "missing_html_lang": "Thiếu thuộc tính lang trên <html>",
    "missing_title": "Thiếu thẻ title",
    "missing_meta_description": "Thiếu meta description / og:description",
    "missing_h1": "Thiếu H1",
    "multiple_h1": "Nhiều thẻ H1",
    "missing_canonical": "Thiếu canonical",
    "title_too_long": "Title quá dài (SERP cắt)",
    "thin_content": "Nội dung mỏng (ít từ)",
    "images_missing_alt": "Ảnh thiếu alt (hoặc alt rỗng không decorative)",
    "soft_404_heuristic": "Soft 404 (HTTP 200 nhưng nội dung 'not found')",
    "duplicate_title": "Trùng title giữa nhiều URL",
    "http_status_error": "HTTP không phải 200",
    "pagination_missing_rel_next": "Phân trang thiếu rel=next",
    "link_check_truncated": "Giới hạn số URL đích kiểm tra liên kết",
    "robots_noindex": "Robots / meta chặn index",
    "indexability_blocked": "Không index được (indexability)",
    "indexability_signal_conflict": "Tín hiệu indexability mâu thuẫn",
    "canonical_cross_host": "Canonical sang host khác",
    "canonical_self_mismatch": "Canonical không khớp URL hiệu dụng (cùng site)",
    "canonical_missing_high_value": "Thiếu canonical (trang giá trị cao)",
    "canonical_points_to_non_indexable": "Canonical trỏ URL đích không indexable",
    "canonical_low_similarity_mismatch": "Canonical khác URL nhưng nội dung rất khác đích",
    "google_may_ignore_canonical": "Google có thể bỏ qua canonical",
    "page_unlikely_indexed": "URL khó được index như bản primary",
    "cloaking_risk_advanced": "Rủi ro cloaking (nâng cao: raw vs rendered)",
    "js_seo_risk_high": "Rủi ro SEO phụ thuộc JS (cao)",
    "js_seo_risk_medium": "Rủi ro SEO phụ thuộc JS (trung bình)",
    "js_shell_missing_critical": "HTML thô thiếu title/meta/H1 sau render",
    "cloaking_heuristic": "Heuristic chênh lệch raw vs rendered",
    "robots_meta_noindex_contradiction": "Mâu thuẫn meta noindex vs indexability",
    "http_status_non_200": "HTTP không 200 nhưng tín hiệu index còn mở",
    "weak_heading_structure": "Cấu trúc heading yếu (ít H2)",
}

SEVERITY_WEIGHT = {"high": 12.0, "medium": 6.0, "low": 2.5}
